import type { Metadata } from "next";
import "./globals.css";
import "./styles.css";
import GlobalFooter from "./components/layout/global-footer";
import GlobalNav from "./components/layout/global-nav";
import Head from "./components/layout/head";
import BottomNav from "./components/layout/bottom-nav";

export const metadata: Metadata = {
  title: "Dan O'Dea Media",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <GlobalNav />
        {children}
        <GlobalFooter />
        <BottomNav />
      </body>
    </html>
  );
}
