export const experience = [
  {
    featured: true,
    id: 1,
    company: "Care/of",
    title: "Software Engineer",
    dates: "June 2022 - present",
    responsibilities: [
      "Contributing to an enterprise grade eCommerce web application",
      "Owned development of a collection of 350+ Articles pages, and related Article Builder tool",
      "Article Builder includes a markdown-based editor that enables business to add pre-built HTML modules to articles published in our CMS, all with the click of a button",
      "Added React Portals to enable the addition of interactive, stateful React components to HTML rendered from markdown created in Article Builder",
    ],
  },
  {
    featured: true,
    id: 2,
    company: "Comcast Business",
    title: "Senior Software Engineer/ Technical Lead",
    dates: "June 2021 - June 2022",
    responsibilities: [
      "Technical Lead/ Front End Engineer on the team that brought our Internet Dashboard to General Availability for 1.8 million users",
      "Led/ mentored a team of three front-end devs as we built features like Internet Speed Test, as well as adding existing components to the experience",
      "Integrated XState with React in order to leverage XState's finite state machines to model the various states and transitions of the Internet Speed Test feature, including idle, loading, success, and error states, mapped to the various stages of the speed test process",
    ],
  },
  {
    featured: true,
    id: 3,
    company: "American Express",
    title: "Software Engineer",
    dates: "June 2020 - June 2021",
    responsibilities: [
      "Contributing to an enterprise grade financial web application",
      "Working in React/ Redux, and learned Angular to contribute to the legacy codebase to maintain existing features while we migrate to React",
      "Personally built the proof of concept that integrated our new React work into the legacy Angular app",
    ],
  },
  {
    featured: false,
    id: 4,
    company: "Vertex Group",
    title: "Senior Software Engineer",
    dates: "Dec 2019 - Apr 2020",
    responsibilities: [
      "Built a world-class social media web application with a feature set that rivals modern social apps",
      "Cultivated experience in working independently as a member of a large scale, distributed team",
      "Worked directly with the head of UX, QA team, project managers and clients to refine existing code in order to meet client expectations",
    ],
  },
  {
    featured: false,
    id: 5,
    company: "Attck/ TimeRepublik",
    title: "Front End Developer",
    dates: "May 2019 - Dec 2019",
    responsibilities: [
      "Developed beautiful interactive web applications and rich web sites in a fast-paced agency setting",
      "Gained experience in working independently as a member of a four-person front-end team",
      "Collaborated with designers, QA team, project managers and clients to ensure client needs are met",
    ],
  },
  {
    featured: false,
    id: 6,
    company: "Crane.ai",
    title: "React Developer",
    dates: "April 2018 - Feb 2019",
    responsibilities: [
      "Received multiple Product of the Month accolades on ProductHunt",
      "Contributed to our full-stack MERN-based AI Website Builder",
      "Built the administrative dashboard from visual design to deployment",
    ],
  },
];
